mode: rule
log-level: info
mixed-port: 7890

proxies:

proxy-groups:
  - name: Proxy
    type: select

rules:
  - DOMAIN-SUFFIX,ipinfo.io,Proxy
  - DOMAIN-SUFFIX,anthropic.com,Proxy
  - MATCH,DIRECT

